#!/usr/bin/env python3
"""
Analysis script for simplified execution logs from tau2-enhanced.

This script uses the new LogAnalyzer and LogVisualizer to process the
execution logs generated by the LoggingEnvironment and produces both
a console report and interactive HTML visualizations.
"""

import argparse
import json
from pathlib import Path
import sys

# Add the parent directory to the path to allow imports from tau2_enhanced
sys.path.append(str(Path(__file__).resolve().parents[1]))

from tau2_enhanced.analysis.analyzer import LogAnalyzer
from tau2_enhanced.analysis.visualizer import LogVisualizer
from tau2_enhanced.logging.events import ToolExecutionEvent


def convert_state_snapshots_to_events(state_snapshots):
    """
    Convert state snapshots to ToolExecutionEvent objects for analysis.

    Args:
        state_snapshots: List of state snapshot objects

    Returns:
        List of ToolExecutionEvent objects that can be analyzed by LogAnalyzer
    """
    events = []

    # Group snapshots by pairs (before/after tool calls)
    for i, snapshot in enumerate(state_snapshots):
        metadata = snapshot.get('metadata', {})
        tool_name = metadata.get('tool_name', 'unknown_tool')

        # Create a ToolExecutionEvent from state snapshot
        if 'before_' in snapshot.get('action_trigger', ''):
            # This is a before snapshot, create a mock ToolExecutionEvent
            event = ToolExecutionEvent(
                timestamp=snapshot.get('timestamp', 0),
                tool_name=tool_name,
                success=True,  # Assume success since we have state changes
                execution_time=0.1,  # Mock execution time
                requestor=metadata.get('requestor', 'assistant'),
                state_changed=True,  # State snapshots imply state change
                result_size=100,  # Mock result size
                args_count=metadata.get('args_count', 0),
                tool_call_id=f"{tool_name}_{i}",
                args_complexity_score=0.3,  # Mock complexity
                result_complexity_score=0.4,
                result_contains_errors=False,
                validation_errors=[]
            )
            events.append(event)

    print(f"   Converted {len(events)} state snapshots to ToolExecutionEvent objects.")
    return events


def analyze_logs(log_file: Path, output_dir: Path):
    """
    Loads, analyzes, and visualizes execution logs from a file.
    """
    print(f"📁 Loading logs from: {log_file}")

    try:
        with log_file.open('r') as f:
            data = json.load(f)
        print(f"  ✅ Successfully loaded log file")
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"❌ Error loading log file: {e}")
        return

    # Detect log format and handle accordingly
    if 'execution_events' in data:
        # New simplified format: direct execution_events array
        print("  📊 Detected new simplified enhanced logs format")

        # Try to load the corresponding standard results file for simulation success data
        if '_enhanced_logs' in log_file.name:
            standard_file = Path(str(log_file).replace('_enhanced_logs', ''))
            try:
                with standard_file.open('r') as f:
                    standard_data = json.load(f)
                print(f"  ✅ Loaded standard results file for simulation data")

                # Add simulation data and tasks to the enhanced logs for analysis
                data['simulations'] = standard_data.get('simulations', [])
                data['tasks'] = standard_data.get('tasks', [])

            except (FileNotFoundError, json.JSONDecodeError) as e:
                print(f"  ⚠️  Could not load standard results file: {e}")

        analyzer_data = data  # Use combined data
    elif 'simulations' in data:
        # Legacy format: simulations with embedded logs
        print("  📊 Detected legacy enhanced logs format")
        analyzer_data = data
    else:
        print("❌ Unrecognized log format - no execution_events or simulations found")
        return

    # The LogAnalyzer is capable of handling different log formats.
    # We pass the entire loaded JSON data to it.
    analyzer = LogAnalyzer(analyzer_data)

    # Check if any tool events were found
    if analyzer.df.empty:
        print("🤷 No tool execution events found in the file.")
        return

    print(f"🔬 Found {len(analyzer.df)} tool execution events to analyze.")
    output_dir.mkdir(parents=True, exist_ok=True)

    # 1. Analyze the logs
    print("\n" + "="*50)
    print("📊 SUMMARY METRICS")
    print("="*50)
    summary = analyzer.get_summary_metrics()
    for key, value in summary.items():
        if isinstance(value, float):
            print(f"  - {key.replace('_', ' ').title()}: {value:.3f}")
        else:
            print(f"  - {key.replace('_', ' ').title()}: {value}")

    print("\n" + "="*50)
    print("🛠️ TOOL PERFORMANCE")
    print("="*50)
    tool_perf = analyzer.get_tool_performance()
    print(tool_perf.to_string(index=False))

    print("\n" + "="*50)
    print("🔥 FAILURE ANALYSIS")
    print("="*50)
    failures = analyzer.get_failure_analysis()
    if not failures.empty:
        print(failures.to_string(index=False))
    else:
        print("  🎉 No failures recorded.")

    print("\n" + "="*50)
    print("🔄 STATE CHANGE ANALYSIS")
    print("="*50)
    state_analysis = analyzer.get_state_change_analysis()
    if not state_analysis.empty:
        print(state_analysis.to_string(index=False))
    else:
        print("  🤷 No state change data available to analyze.")

    print("\n" + "="*50)
    print("🔗 TOOL SEQUENCE ANALYSIS")
    print("="*50)
    sequence_analysis = analyzer.get_tool_sequence_analysis()
    if not sequence_analysis.empty:
        print("  Top 10 most common tool transitions:")
        print(sequence_analysis.head(10).to_string(index=False))
    else:
        print("  🤷 Not enough data to analyze tool sequences.")

    # 2. Visualize the results
    print("\n" + "="*50)
    print("📈 GENERATING VISUALIZATIONS")
    print("="*50)
    visualizer = LogVisualizer(analyzer)

    try:
        # Core Reports - Generated by default

        # Comprehensive Tool Report
        tool_report_path = output_dir / "tool_report.html"
        visualizer.create_tool_report(str(tool_report_path), log_file.name)
        print(f"  ✅ Comprehensive tool report saved to: {tool_report_path}")

        # Markdown Report
        markdown_path = output_dir / "analysis_report.md"
        visualizer.create_markdown_report(str(markdown_path), log_file.name)
        print(f"  ✅ Markdown analysis report saved to: {markdown_path}")

        # Enhanced Analysis Report
        enhanced_report_path = output_dir / "enhanced_analysis_report.html"
        visualizer.create_enhanced_analysis_report(str(enhanced_report_path), log_file.name)
        print(f"  ✅ Enhanced analysis report with plots saved to: {enhanced_report_path}")

        # Optional individual plots (commented out by default)
        # Uncomment these for additional detailed visualizations:
        #
        # summary_fig = visualizer.create_summary_dashboard()
        # summary_path = output_dir / "summary_dashboard.html"
        # summary_fig.write_html(summary_path)
        # print(f"  ✅ Summary dashboard saved to: {summary_path}")
        #
        # failure_fig = visualizer.create_failure_analysis_plot()
        # failure_path = output_dir / "failure_analysis.html"
        # failure_fig.write_html(failure_path)
        # print(f"  ✅ Failure analysis plot saved to: {failure_path}")
        #
        # state_change_fig = visualizer.create_state_change_plot()
        # state_change_path = output_dir / "state_change_analysis.html"
        # state_change_fig.write_html(state_change_path)
        # print(f"  ✅ State change analysis plot saved to: {state_change_path}")
        #
        # sankey_fig = visualizer.create_tool_flow_sankey()
        # sankey_path = output_dir / "tool_flow_sankey.html"
        # sankey_fig.write_html(sankey_path)
        # print(f"  ✅ Tool flow Sankey diagram saved to: {sankey_path}")
        #
        # bottleneck_fig = visualizer.create_performance_bottleneck_plot()
        # bottleneck_path = output_dir / "performance_bottlenecks.html"
        # bottleneck_fig.write_html(bottleneck_path)
        # print(f"  ✅ Performance bottleneck plot saved to: {bottleneck_path}")

        # Comprehensive simulation report with action check analysis
        sim_report_path = output_dir / "simulation_report.html"
        visualizer.create_comprehensive_simulation_report_html(str(sim_report_path))
        print(f"  ✅ Comprehensive simulation report saved to: {sim_report_path}")

    except Exception as e:
        print(f"  ❌ Error during visualization: {e}")

    print("\n🎉 Analysis complete!")
    print(f"\n🛠️ For a detailed tool analysis, open: {output_dir / 'tool_report.html'}")
    print(f"🚀 For enhanced analysis with interactive plots, open: {output_dir / 'enhanced_analysis_report.html'}")
    print(f"📋 For a markdown summary report, see: {output_dir / 'analysis_report.md'}")
    print(f"📊 For simulation-level action check analysis, open: {output_dir / 'simulation_report.html'}")


def main():
    parser = argparse.ArgumentParser(
        description="Analyze simplified execution logs from tau2-enhanced."
    )
    parser.add_argument(
        "log_file",
        type=Path,
        help="Path to the JSON results file containing execution_logs."
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        default=None,
        help="Output directory to save analysis results. If not specified, uses 'analysis_results/<log_file_stem>'."
    )
    parser.add_argument(
        "-n", "--name",
        type=str,
        default=None,
        help="Custom name for the output subdirectory. If not specified, uses the log file stem."
    )
    args = parser.parse_args()

    # Determine output directory
    if args.output:
        # User specified output directory - use it directly
        output_subdir = args.output
    else:
        # Default behavior: create subfolder based on log file name or custom name
        base_dir = Path("analysis_results")
        subdir_name = args.name if args.name else args.log_file.stem
        output_subdir = base_dir / subdir_name

    print(f"💾 Output will be saved to: {output_subdir}")

    analyze_logs(args.log_file, output_subdir)


if __name__ == "__main__":
    main()
