#!/usr/bin/env python3
"""
Reduce the size of tau2-bench log files by keeping only fields needed for analysis.

This script extracts the minimal required fields from large log files generated by
tau2-bench-jit, keeping only what's needed for analyze_simple_logs.py to work.
"""

import argparse
import json
from pathlib import Path


def reduce_log_file(input_file: Path, output_file: Path):
    """
    Reduce log file size by keeping only essential fields.

    Required fields for analyze_simple_logs.py:
    - execution_events (array of tool execution events)
    - simulations (array with reward, task_id, trial, action_checks)
    - tasks (array - optional but useful)
    """
    print(f"📁 Loading: {input_file}")

    try:
        with input_file.open('r') as f:
            data = json.load(f)
        print(f"  ✅ Loaded {input_file.stat().st_size / 1024 / 1024:.2f} MB")
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"❌ Error loading file: {e}")
        return

    # Create reduced data structure
    reduced_data = {}

    # Keep execution_events if present
    if 'execution_events' in data:
        reduced_data['execution_events'] = data['execution_events']
        print(f"  📊 Kept {len(data['execution_events'])} execution events")

    # Reduce simulations - keep only essential fields
    if 'simulations' in data:
        reduced_sims = []
        for sim in data['simulations']:
            reduced_sim = {
                'reward': sim.get('reward', 0),
                'task_id': sim.get('task_id'),
                'trial': sim.get('trial'),
            }

            # Keep execution_logs if present (essential for tool analysis)
            if 'execution_logs' in sim:
                reduced_sim['execution_logs'] = sim['execution_logs']
                # Add flag to indicate this is tau2-bench-jit format with enhanced logging
                reduced_sim['enhanced_logging_enabled'] = True

            # Keep messages if present (needed for simulation report message logs)
            # Strip out raw_data from messages to save space
            if 'messages' in sim:
                reduced_messages = []
                for msg in sim['messages']:
                    reduced_msg = {k: v for k, v in msg.items() if k != 'raw_data'}
                    reduced_messages.append(reduced_msg)
                reduced_sim['messages'] = reduced_messages

            # Keep action_checks if present (needed for action validation analysis)
            if 'action_checks' in sim:
                reduced_sim['action_checks'] = sim['action_checks']

            # Keep reward_info if present (contains detailed reward breakdown)
            if 'reward_info' in sim:
                reduced_sim['reward_info'] = sim['reward_info']

            # Keep other minimal fields that might be needed
            for key in ['duration', 'termination', 'termination_reason', 'agent_cost', 'user_cost']:
                if key in sim:
                    reduced_sim[key] = sim[key]

            reduced_sims.append(reduced_sim)

        reduced_data['simulations'] = reduced_sims
        print(f"  🎯 Reduced {len(reduced_sims)} simulations")

    # Keep tasks array if present (useful for analysis)
    if 'tasks' in data:
        reduced_data['tasks'] = data['tasks']
        print(f"  📋 Kept {len(data['tasks'])} tasks")

    # Keep metadata if present
    if 'metadata' in data:
        reduced_data['metadata'] = data['metadata']
        print(f"  ℹ️  Kept metadata")

    # Write reduced file
    print(f"\n💾 Writing reduced file: {output_file}")
    with output_file.open('w') as f:
        json.dump(reduced_data, f, indent=2)

    output_size = output_file.stat().st_size / 1024 / 1024
    input_size = input_file.stat().st_size / 1024 / 1024
    reduction = (1 - output_size / input_size) * 100

    print(f"  ✅ Saved {output_size:.2f} MB")
    print(f"  📉 Reduced by {reduction:.1f}% (from {input_size:.2f} MB)")


def main():
    parser = argparse.ArgumentParser(
        description="Reduce tau2-bench log file size by keeping only analysis-required fields"
    )
    parser.add_argument(
        "input_file",
        type=Path,
        help="Path to the large log file to reduce"
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        default=None,
        help="Output file path. If not specified, adds '_reduced' suffix to input filename"
    )

    args = parser.parse_args()

    # Determine output path
    if args.output:
        output_file = args.output
    else:
        # Add _reduced suffix before extension
        stem = args.input_file.stem
        suffix = args.input_file.suffix
        output_file = args.input_file.parent / f"{stem}_reduced{suffix}"

    reduce_log_file(args.input_file, output_file)

    print(f"\n🎉 Done! Reduced file ready for analysis:")
    print(f"   python3 scripts/analyze_simple_logs.py {output_file}")


if __name__ == "__main__":
    main()
