#!/usr/bin/env python3
"""
Reduce the size of tau2-bench log files by keeping only fields needed for analysis.

This script extracts the minimal required fields from large log files generated by
tau2-bench-jit, keeping only what's needed for analyze_simple_logs.py to work.
"""

import argparse
import json
from pathlib import Path


def reduce_log_file(input_file: Path, output_file: Path):
    """
    Reduce log file size by keeping only essential fields.

    Keeps all standard tau2 Results fields required by analyze_breakdown.py and failure_analysis.py.
    Removes only unused enhanced logging fields: state_snapshots, context_usage_snapshots, execution_metrics.

    Required top-level fields:
    - timestamp, info, tasks, simulations (standard Results structure)

    Required simulation fields (standard tau2 SimulationRun):
    - id, task_id, timestamp, start_time, end_time, duration, termination_reason
    - agent_cost, user_cost, reward_info, messages, trial, seed

    Additional fields kept for enhanced analysis:
    - execution_logs (used by tau2_enhanced/analysis/analyzer.py)
    - enhanced_logging_enabled flag (used to detect format)
    """
    print(f"📁 Loading: {input_file}")

    try:
        with input_file.open('r') as f:
            data = json.load(f)
        print(f"  ✅ Loaded {input_file.stat().st_size / 1024 / 1024:.2f} MB")
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"❌ Error loading file: {e}")
        return

    # Create reduced data structure - preserve standard Results format
    reduced_data = {}

    # Keep top-level Results fields (required by tau2.data_model.simulation.Results)
    for key in ['timestamp', 'info']:
        if key in data:
            reduced_data[key] = data[key]

    # Keep execution_events if present (for enhanced logging)
    if 'execution_events' in data:
        reduced_data['execution_events'] = data['execution_events']
        print(f"  📊 Kept {len(data['execution_events'])} execution events")

    # Reduce simulations - keep all standard fields plus execution_logs
    if 'simulations' in data:
        reduced_sims = []
        removed_fields_count = 0

        for sim in data['simulations']:
            reduced_sim = {}

            # Keep ALL standard tau2 SimulationRun fields (required by Results.load())
            standard_fields = [
                'id', 'task_id', 'timestamp', 'start_time', 'end_time',
                'duration', 'termination_reason', 'agent_cost', 'user_cost',
                'reward_info', 'messages', 'trial', 'seed'
            ]

            for key in standard_fields:
                if key in sim:
                    if key == 'messages':
                        # Strip raw_data from messages to save space
                        reduced_messages = []
                        for msg in sim['messages']:
                            reduced_msg = {k: v for k, v in msg.items() if k != 'raw_data'}
                            reduced_messages.append(reduced_msg)
                        reduced_sim['messages'] = reduced_messages
                    else:
                        reduced_sim[key] = sim[key]

            # Keep enhanced logging fields that are actually used
            if 'execution_logs' in sim:
                reduced_sim['execution_logs'] = sim['execution_logs']
                reduced_sim['enhanced_logging_enabled'] = True

            # Remove unused enhanced logging fields
            for unused_field in ['state_snapshots', 'context_usage_snapshots', 'execution_metrics']:
                if unused_field in sim:
                    removed_fields_count += 1

            reduced_sims.append(reduced_sim)

        reduced_data['simulations'] = reduced_sims
        print(f"  🎯 Reduced {len(reduced_sims)} simulations")
        print(f"  🗑️  Removed {removed_fields_count} unused enhanced logging fields")

    # Keep tasks array if present (required by Results)
    if 'tasks' in data:
        reduced_data['tasks'] = data['tasks']
        print(f"  📋 Kept {len(data['tasks'])} tasks")

    # Keep metadata if present (optional but useful)
    if 'metadata' in data:
        reduced_data['metadata'] = data['metadata']
        print(f"  ℹ️  Kept metadata")

    # Write reduced file
    print(f"\n💾 Writing reduced file: {output_file}")
    with output_file.open('w') as f:
        json.dump(reduced_data, f, indent=2)

    output_size = output_file.stat().st_size / 1024 / 1024
    input_size = input_file.stat().st_size / 1024 / 1024
    reduction = (1 - output_size / input_size) * 100

    print(f"  ✅ Saved {output_size:.2f} MB")
    print(f"  📉 Reduced by {reduction:.1f}% (from {input_size:.2f} MB)")


def main():
    parser = argparse.ArgumentParser(
        description="Reduce tau2-bench log file size by keeping only analysis-required fields"
    )
    parser.add_argument(
        "input_file",
        type=Path,
        help="Path to the large log file to reduce"
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        default=None,
        help="Output file path. If not specified, adds '_reduced' suffix to input filename"
    )

    args = parser.parse_args()

    # Determine output path
    if args.output:
        output_file = args.output
    else:
        # Add _reduced suffix before extension
        stem = args.input_file.stem
        suffix = args.input_file.suffix
        output_file = args.input_file.parent / f"{stem}_reduced{suffix}"

    reduce_log_file(args.input_file, output_file)

    print(f"\n🎉 Done! Reduced file ready for analysis:")
    print(f"   python3 scripts/analyze_simple_logs.py {output_file}")


if __name__ == "__main__":
    main()
